export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";
export const GET_MOVIES = "GET_MOVIES";
export const SET_TOTAL = "SET_TOTAL";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const INCREMENT_CURRENT_PAGE = "INCREMENT_CURRENT_PAGE";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
